#!/bin/sh
# (q.03)
# Afin d'executer ce script dans le shell courant et non dans un fork de
# celui-ci, lancez ". ./03" ou "source ./03"
# https://docs.docker.com/machine/get-started/#create-a-machine
# Si necessaire, retirez prealablement ces variables de l'environnement courant du terminal :
# eval "$(docker-machine env -u)"
eval "$(docker-machine env Char)"
