#!/bin/sh
# (q.06)
# GNU Linux Magazine France - Hors Serie 98 - Pages 49 (-d, --net=bridge -p 5000:80), 51 (--name), 54 (--restart=unless-stopped)
docker run --name overlord -d --net=bridge -p 5000:80 --restart=unless-stopped nginx
