#!/bin/sh
# (q.13)
# GNU Linux Magazine France - Hors Serie 98 - Page 51 (--volumes-from)
# https://hub.docker.com/_/wordpress/
# echo "http://$(docker-machine ip Char):8080"
docker run --name lair -d \
	--link spawning-pool:mysql \
	--net=bridge -p 8080:80 \
	wordpress
