#!/bin/sh
# (q.26)
# https://hub.docker.com/r/42school/engineering-bay/
# https://docs.docker.com/network/network-tutorial-overlay/
docker service create --name engineering-bay \
	-e OC_USERNAME=Jim_Raynor \
	-e OC_PASSWD=Kerrigan \
	--replicas=2 \
	--network overmind \
	42school/engineering-bay
