#!/bin/sh
#Commandes alternatives :
#	dig slash16.org. ns
#	host -v -t ns slash16.org.
#	nslookup -querytype=ns slash16.org.
nslookup -querytype=ns slash16.org. | awk '/internet address/ { print $NF }'
