#!/bin/sh
#04.	Identifiez la gateway par defaut dans la table de routage
#	-r :
#		Show the routing tables
#	-f inet :
#		Limit statistics or address control block reports to those of 'inet'
netstat -r -f inet | awk '/^default/ { print $2 }'
