#!/bin/sh
#04.	Realiser un script qui permet de surveiller les modifications du fichier
#		/etc/crontab et envoie un mail a root si celui-ci a ete modifie. Creez
#		une tache planifiee pour ce script tous les jours a minuit
SCRIPT_FILE=/root/monitor_crontab.sh
CRONTAB_TEMPORARY_FILE=/tmp/crontab.tmp
rm -f $SCRIPT_FILE
echo '#!/bin/sh' > $SCRIPT_FILE
echo 'OLD_CHKSUM=`cat /root/checksum_crontab.tmp`' >> $SCRIPT_FILE
echo "NEW_CHKSUM=\`md5sum /etc/crontab | awk '{ print \$1 }'\`" >> $SCRIPT_FILE
echo 'if test "x$NEW_CHKSUM" != "x$OLD_CHKSUM" ; then' >> $SCRIPT_FILE
echo "\tmail -s \"La crontab pour root a ete modifiee\"\
	root@localhost < /etc/crontab" >> $SCRIPT_FILE
echo "\techo \"\$NEW_CHKSUM\" > /root/checksum_crontab.tmp" >> $SCRIPT_FILE
echo 'fi' >> $SCRIPT_FILE
chmod u+x $SCRIPT_FILE
rm -f $CRONTAB_TEMPORARY_FILE
crontab -l > $CRONTAB_TEMPORARY_FILE
echo "0 0 * * * sh $SCRIPT_FILE" >> $CRONTAB_TEMPORARY_FILE
crontab $CRONTAB_TEMPORARY_FILE
rm -f $CRONTAB_TEMPORARY_FILE
