#!/bin/sh
#04.	Realiser un script qui permet de surveiller les modifications du fichier
#		/etc/crontab et envoie un mail a root si celui-ci a ete modifie. Creez
#		une tache planifiee pour ce script tous les jours a minuit
SCRIPT_FILE="~/`basename ${0}`"
CRONTAB_LINE="0 0 * * * ${SCRIPT_FILE} LAUNCH"
CRONTAB_TEMPORARY_FILE=/tmp/crontab.tmp
CHKSUM_FILE=~/crontab.chksum

usage () {
	echo "usage: ${0} [LAUNCH]"
}

if test ${#} -gt 1 || ( test ${#} -eq 1 && test "xS{1}" != 'xLAUNCH' ) ; then
	usage
elif test ${#} -eq 0 ; then
	if test "x`crontab -l | awk -v AWK_CRONTAB_LINE=\"${CRONTAB_LINE}\" '/^$(AWK_CRONTAB_LINE)$/ { print $(0) }'`" = "x${CRONTAB_LINE}" ; then
		echo 'Tache deja presente dans la crontab'
	else
		rm -f ${CRONTAB_TEMPORARY_FILE}
		crontab -l > ${CRONTAB_TEMPORARY_FILE}
		echo "${CRONTAB_LINE}" >> ${CRONTAB_TEMPORARY_FILE}
		crontab ${CRONTAB_TEMPORARY_FILE}
		rm -f ${CRONTAB_TEMPORARY_FILE}
	fi
else
	OLD_CHKSUM=`cat ${CHKSUM_FILE}`
	NEW_CHKSUM=`md5sum /etc/crontab | awk '{ print $(1) }'`
	if test "x${NEW_CHKSUM}" != "x${OLD_CHKSUM}" ; then
		mail -s 'La crontab pour cet utilisateur a ete modifiee' root@localhost < `{ date ; echo '' ; cat /etc/crontab ; }`
		echo "${NEW_CHKSUM}" > ${CHKSUM_FILE}
	fi
fi
